# Dockerfile to create ssh connection from Docker host

FROM centos:7

RUN yum install openssh-server -y

RUN useradd remote_user && \
    echo "1234" | passwd remote_user  --stdin && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh

COPY remote-key.pub /home/remote_user/.ssh/authorized.keys

RUN chown remote_user:remote_user -R /home/remote_user/.ssh && \
    chmod 600 /home/remote_user/.ssh/authorized.keys

RUN /usr/sbin/sshd-keygen

CMD /usr/sbin/sshd -D
